#define GM_HOST_NAME    "[0.3.DL] Los Santos Roleplay LITE | เข้าสู่ระบบด้วย UCP"
#define GM_VERSION      "0.0.2" // x.y.z

#define IN_GAME_REGISTER 			// สมัครสมาชิกในเกม
//#define	IN_GAME_CREATE_CHARACTER	// สร้างตัวละครในเกม 

// ถ้าไม่ต้องการให้ `//` ปิดไว้

/*	z - แก้ไขบัคเล็กน้อย
	y - อัปเดต / ฟีเจอร์ ใหม่เล็ก ๆ
	x - ฟีเจอร์ใหม่
*/

// ระยะทางที่เห็นชื่อ
#define NAME_TAG_DISTANCE				2.5

#define DEFAULT_SPAWN_LOCATION_X		1642.2770
#define DEFAULT_SPAWN_LOCATION_Y		-2332.8931
#define DEFAULT_SPAWN_LOCATION_Z		-2.6797
#define DEFAULT_SPAWN_LOCATION_A		0.0

#define TIMEOUT_CRASH_TIME				30 // หน่วย: นาที | ผู้เล่นกลับมาภายในเวลาที่กำหนดจะถูกส่งกลับตำแหน่งล่าสุด
#define DEFAULT_PLAYER_CASH				5000 // เงินเริ่มต้น
#define	DEFAULT_PLAYER_LOGIN_ATTEMPT	5 // การจำกัดการพยายามเข้าสู่ระบบ

#define	EXP_MULTIPLE_RATE				2 // เรทการขึ้นเลเวล

#define MYSQL_CHARSET           "tis620"