CREATE TABLE IF NOT EXISTS `business` (
  `BusinessDBID` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `BusinessName` varchar(90) NOT NULL,
  `BusinessOwnerDBID` int(11) NOT NULL DEFAULT 0,
  `BusinessType` int(11) NOT NULL,
  `BusinessPrice` int(11) NOT NULL DEFAULT 5000,
  `BusinessLevel` int(11) NOT NULL DEFAULT 1,
  `BusinessEntrancePrice` int(11) NOT NULL DEFAULT 200,
  `BusinessLock` int(11) NOT NULL,
  `BusinessS_Cemara` int(11) NOT NULL,
  `BusinessS_Mask` int(11) NOT NULL,
  `BusinessS_Flower` int(11) NOT NULL,
  `BusinessEntranceX` float NOT NULL,
  `BusinessEntranceY` float NOT NULL,
  `BusinessEntranceZ` float NOT NULL,
  `BusinessEntranceWorld` int(11) NOT NULL,
  `BusinessEntranceInterior` int(11) NOT NULL,
  `BusinessInteriorX` float NOT NULL,
  `BusinessInteriorY` float NOT NULL,
  `BusinessInteriorZ` float NOT NULL,
  `BusinessInteriorWorld` int(11) NOT NULL,
  `BusinessInteriorID` int(11) NOT NULL,
  `BusinessBankPickupLocX` float NOT NULL,
  `BusinessBankPickupLocY` float NOT NULL,
  `BusinessBankPickupLocZ` float NOT NULL,
  `BusinessBankWorld` int(11) NOT NULL,
  `BusinessCash` int(11) NOT NULL,
    PRIMARY KEY
        (BusinessDBID)
);