CREATE TABLE IF NOT EXISTS `house` (
  `HouseDBID` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `HouseName` varchar(90) COLLATE utf8mb4_croatian_ci NOT NULL,
  `HouseOwnerDBID` int(11) NOT NULL,
  `HouseEntranceX` float NOT NULL,
  `HouseEntranceY` float NOT NULL,
  `HouseEntranceZ` float NOT NULL,
  `HouseEntranceWorld` int(11) NOT NULL,
  `HouseEntranceInterior` int(11) NOT NULL,
  `HouseInteriorX` float NOT NULL,
  `HouseInteriorY` float NOT NULL,
  `HouseInteriorZ` float NOT NULL,
  `HouseInteriorWorld` int(11) NOT NULL,
  `HouseInteriorID` int(11) NOT NULL,
  `HousePrice` int(11) NOT NULL,
  `HouseLevel` int(11) NOT NULL,
  `HouseLock` int(11) NOT NULL,
  `HouseEle` int(11) NOT NULL DEFAULT 0,
  `HouseStockCPU` int(11) NOT NULL DEFAULT 0,
  `HouseStockGPU` int(11) NOT NULL DEFAULT 0,
  `HouseStockRAM` int(11) NOT NULL DEFAULT 0,
  `HouseStockStored` int(11) NOT NULL DEFAULT 0,
  `HousePlacePosX` float NOT NULL,
  `HousePlacePosY` float NOT NULL,
  `HousePlacePosZ` float NOT NULL,
  `HouseWeapons1` int(11) NOT NULL,
  `HouseWeapons2` int(11) NOT NULL,
  `HouseWeapons3` int(11) NOT NULL,
  `HouseWeapons4` int(11) NOT NULL,
  `HouseWeapons5` int(11) NOT NULL,
  `HouseWeapons6` int(11) NOT NULL,
  `HouseWeapons7` int(11) NOT NULL,
  `HouseWeapons8` int(11) NOT NULL,
  `HouseWeapons9` int(11) NOT NULL,
  `HouseWeapons10` int(11) NOT NULL,
  `HouseWeapons11` int(11) NOT NULL,
  `HouseWeapons12` int(11) NOT NULL,
  `HouseWeapons13` int(11) NOT NULL,
  `HouseWeapons14` int(11) NOT NULL,
  `HouseWeapons15` int(11) NOT NULL,
  `HouseWeapons16` int(11) NOT NULL,
  `HouseWeapons17` int(11) NOT NULL,
  `HouseWeapons18` int(11) NOT NULL,
  `HouseWeapons19` int(11) NOT NULL,
  `HouseWeapons20` int(11) NOT NULL,
  `HouseWeapons21` int(11) NOT NULL,
  `HouseWeaponsAmmo1` int(11) NOT NULL,
  `HouseWeaponsAmmo2` int(11) NOT NULL,
  `HouseWeaponsAmmo3` int(11) NOT NULL,
  `HouseWeaponsAmmo4` int(11) NOT NULL,
  `HouseWeaponsAmmo5` int(11) NOT NULL,
  `HouseWeaponsAmmo6` int(11) NOT NULL,
  `HouseWeaponsAmmo7` int(11) NOT NULL,
  `HouseWeaponsAmmo8` int(11) NOT NULL,
  `HouseWeaponsAmmo9` int(11) NOT NULL,
  `HouseWeaponsAmmo10` int(11) NOT NULL,
  `HouseWeaponsAmmo11` int(11) NOT NULL,
  `HouseWeaponsAmmo12` int(11) NOT NULL,
  `HouseWeaponsAmmo13` int(11) NOT NULL,
  `HouseWeaponsAmmo14` int(11) NOT NULL,
  `HouseWeaponsAmmo15` int(11) NOT NULL,
  `HouseWeaponsAmmo16` int(11) NOT NULL,
  `HouseWeaponsAmmo17` int(11) NOT NULL,
  `HouseWeaponsAmmo18` int(11) NOT NULL,
  `HouseWeaponsAmmo19` int(11) NOT NULL,
  `HouseWeaponsAmmo20` int(11) NOT NULL,
  `HouseWeaponsAmmo21` int(11) NOT NULL,
    PRIMARY KEY
      (HouseDBID)
);